### ISSUE TITLE
Values copied using copyProperties method of a DictionaryInterface refers to same memory space

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/soma-io#10]
Hello,

I am not sure that this is a bug, but it is quite confusing.
In the following example, their is 2 PropertySet. The 1st one contains a property (named property1) with an integer value.
the 2nd one is copied from the first. If I modify the value of property1 in the 2nd PropertySet, the property1 value is also modified in the 1st PropertySet.
Is it the wanted behaviour ? For atomic objects, value should'nt it be copied ?

Here is the example to reproduce the issue :
````c++
//--- std --------------------------------------------------------------------
#include <iostream>
#include <vector>
//--- cartobase --------------------------------------------------------------
#include <cartobase/object/property.h>
#include <cartobase/config/verbose.h>
//----------------------------------------------------------------------------

using namespace std;
using namespace carto;

#define TEST_1 1

template <class T>
void displayVector(const std::vector<T> & vec) {
    std::cout << "[";
    for(int i=0; i<vec.size()-1; i++)
        std::cout << carto::toString(vec[i]) << ", ";
    if (vec.size() > 0)
        std::cout << carto::toString(vec[vec.size() - 1]);
    std::cout << "]"
              << std::endl << std::flush;
}

template <class T>
void displayDict(const Object d) {
    Object iterator = d->objectIterator();
    std::cout << "{";
    while(iterator->isValid())
    {
        std::cout << iterator->key() 
                    << ": " << toString(iterator->currentValue()->value<T>());
        iterator->next();
        
        if (iterator->isValid())
            std::cout << "," << std::endl;
    }
    std::cout << "}" << std::endl;
}

#ifdef TEST_1
#pragma message "Building Test 1"


int test_1() {
    std::cout 
        << "+------------------------------------------------+" << std::endl
        << "| Test 1"                                           << std::endl
        << "+------------------------------------------------+" << std::endl;
    
    carto::verbose = 1;
    carto::debugMessageLevel = 100;

    int v=0;
    Object p = Object::value(PropertySet());
    p->setProperty("property1", v);
    
    std::cout << "1st property set content before copy:" << std::endl;
    displayDict<int>(p);
    
    Object p2 = Object::value(PropertySet());
    p2->copyProperties(p);
    p2->getProperty("property1")->value<int>() += 1;
    
    std::cout << "1st property set content after copy:" << std::endl;
    displayDict<int>(p);
    
    std::cout << "2nd property set content after copy:" << std::endl;
    displayDict<int>(p2);
    //std::cout << "2nd property set:" << std::endl;    
    
    
    std::cout 
        << "+------------------------------------------------+" << std::endl
        << "| End test 1"                                       << std::endl
        << "+------------------------------------------------+" << std::endl;
        
    return 0;
}
#endif

int main( int argc, const char **argv )
{
#ifdef TEST_1
    test_1();
#endif
    return 0;
}
```

Output of the example is :
```
+------------------------------------------------+
| Test 1
+------------------------------------------------+
1st property set content before copy:
{property1: 0}
1st property set content after copy:
{property1: 1}
2nd property set content after copy:
{property1: 1}
+------------------------------------------------+
| End test 1
+------------------------------------------------+
```

**Comment by denisri** [comment]
No it's not a bug, it is actually the expected behaviour. For 2 reasons:
* The "intentional" reason: `copyProperties()` is made firstly to perform a "shallow copy" and we needed a means to do so. Another function, like "`deepCopyProperties()`" could be thought of for a deep copy procedure, it it was existing (or was added one day).
* The "technical" reason: in generic objects we can store any kind of objects in properties. We do not have a means of copying every type of object, and moreover in C++ many objects can simply not be copied/duplicated because they don't define copy operators or copy constructors. An additional difficulty is that the generic object is a wrapper for a template type, itself stored as value, or reference, or pointer, and the copy mechanism is very difficult (maybe impossible) to implement in a generic way. Thus "`deepCopyProperties()`" is probably difficult or impossible to implement.

In comparison, `PropertySet` is very similar to a python dictionary. Python dictionaries copies (either via the constructor or using `copy.copy(dict_instance)` perform a shallow copy (unless `copy.deepcopy()` is used), but for numeric values it seems to behave like copies: for instance:
```
>>> import copy
>>> l = [1,2,3,4]
>>> d = {'list': [1, 2, 3, 4], 'int': 12}
>>> d2 = copy.copy(d)
>>> d['list'][1] += 1
>>> d['int'] += 1
>>> print(d)
{'list': [1, 3, 3, 4], 'int': 13}
>>> print(d2)
{'list': [1, 3, 3, 4], 'int': 12}
```
thus ints and numeric values are copied, but "objects" are shared. This is not very consistent but we are used to it. `PropertySet` has a "more consistent" behaviour: everything is shallow copy.

**Comment by nsouedet** [comment]
Many thanks Denis, so I close this
