### ISSUE TITLE
unable to read Nifti files whose name is shorter than 7 characters

### ISSUE THREAD

**Issue by ylep** [brainvisa/soma-io#9]
In BrainVISA 5.0.1 we get an error when trying to read any Nifti file whose basename is shorter than 7 characters:

- `AimsFileInfo a.nii` fails
- `AimsFileInfo ab.nii` fails
- `AimsFileInfo abc.nii` works
- `AimsFileInfo a.nii.gz` also works

In a quick scan I have been unable to find the guilty code, and I won't have time to look into this during the next days, so any help would be appreciated (@denisri ? ;-)

@brainvisa/release This is a serious regression that probably mandates a 5.0.2 release...

**Comment by denisri** [comment]
I confirm I reproduce the bug, and I've been struggling on it since this morning...

**Comment by denisri** [comment]
OK I found it: the problem was not at all in the nifti header checker, but in `DataSourceLoader::check()`.
The IO system is so complex that we're easily lost in it... and there are many operations done multiple times (which adds overhead and confuzion in debugging)
I'm removing debug prints before I commit the fix...
